"""empty message

Revision ID: b655031c07ac
Revises: 38808062426b
Create Date: 2024-11-18 23:30:07.674925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b655031c07ac'
down_revision = '38808062426b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('media_name')

    # ### end Alembic commands ###
